# Generated by Django 3.1.1 on 2020-09-27 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('classification', models.CharField(default='animal', max_length=30)),
                ('image', models.ImageField(null=True, upload_to='products/images')),
                ('status', models.CharField(default='deactive', max_length=30)),
                ('added_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('description', models.TextField(null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.CharField(max_length=30, null=True)),
                ('age_range', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('chemical_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('classification', models.CharField(default='chemical', max_length=30)),
                ('image', models.ImageField(null=True, upload_to='products/images')),
                ('status', models.CharField(default='deactive', max_length=30)),
                ('added_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('description', models.TextField(null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('weight', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('coffee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('classification', models.CharField(default='coffee', max_length=30)),
                ('image', models.ImageField(null=True, upload_to='products/images')),
                ('status', models.CharField(default='deactive', max_length=30)),
                ('added_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('description', models.TextField(null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('coffee_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('classification', models.CharField(default='material', max_length=30)),
                ('image', models.ImageField(null=True, upload_to='products/images')),
                ('status', models.CharField(default='deactive', max_length=30)),
                ('added_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('description', models.TextField(null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('shippingfee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.CharField(default='g', max_length=5)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('animal_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_shipping_fees', to='kwetuTrade.animal')),
                ('chemical_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_shipping_fees', to='kwetuTrade.chemical')),
                ('coffee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffee_shipping_fees', to='kwetuTrade.coffee')),
                ('material_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_shipping_fees', to='kwetuTrade.material')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCountryPrice',
            fields=[
                ('shippingcountryprice_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippingcountryprices', to='kwetuTrade.shippingfee')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeWeight',
            fields=[
                ('unit_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coffee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffeeweights', to='kwetuTrade.coffee')),
            ],
        ),
    ]
