# Generated by Django 3.1.1 on 2020-09-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeweight',
            old_name='coffee_ID',
            new_name='coffee',
        ),
        migrations.RenameField(
            model_name='shippingcountryprice',
            old_name='shipping_fee_ID',
            new_name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='animal_ID',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='chemical_ID',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='coffee_ID',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='material_ID',
        ),
        migrations.AddField(
            model_name='shippingfee',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_shipping_fees', to='kwetuTrade.animal'),
        ),
        migrations.AddField(
            model_name='shippingfee',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_shipping_fees', to='kwetuTrade.chemical'),
        ),
        migrations.AddField(
            model_name='shippingfee',
            name='coffee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffee_shipping_fees', to='kwetuTrade.coffee'),
        ),
        migrations.AddField(
            model_name='shippingfee',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_shipping_fees', to='kwetuTrade.material'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='chemical_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='coffee_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coffeeweight',
            name='unit_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingcountryprice',
            name='shippingcountryprice_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='shippingfee_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
