# Generated by Django 3.1.1 on 2020-09-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0006_auto_20200929_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalShippingCountryPrice',
            fields=[
                ('shippingcountryprice_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalShippingFee',
            fields=[
                ('shippingfee_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('unit', models.CharField(default='g', max_length=5)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_shipping_fees', to='kwetuTrade.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalShippingCountryPrice',
            fields=[
                ('shippingcountryprice_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalShippingFee',
            fields=[
                ('shippingfee_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('unit', models.CharField(default='g', max_length=5)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_shipping_fees', to='kwetuTrade.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeShippingCountryPrice',
            fields=[
                ('shippingcountryprice_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeShippingFee',
            fields=[
                ('shippingfee_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('unit', models.CharField(default='g', max_length=5)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('coffee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffee_shipping_fees', to='kwetuTrade.coffee')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialShippingCountryPrice',
            fields=[
                ('shippingcountryprice_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialShippingFee',
            fields=[
                ('shippingfee_ID', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('unit', models.CharField(default='g', max_length=5)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_shipping_fees', to='kwetuTrade.material')),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='material',
        ),
        migrations.DeleteModel(
            name='ShippingCountryPrice',
        ),
        migrations.DeleteModel(
            name='ShippingFee',
        ),
        migrations.AddField(
            model_name='materialshippingcountryprice',
            name='material_shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialshippingcountryprices', to='kwetuTrade.materialshippingfee'),
        ),
        migrations.AddField(
            model_name='coffeeshippingcountryprice',
            name='coffee_shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffeeshippingcountryprices', to='kwetuTrade.coffeeshippingfee'),
        ),
        migrations.AddField(
            model_name='chemicalshippingcountryprice',
            name='chemical_shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemicalshippingcountryprices', to='kwetuTrade.chemicalshippingfee'),
        ),
        migrations.AddField(
            model_name='animalshippingcountryprice',
            name='animal_shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animalshippingcountryprices', to='kwetuTrade.animalshippingfee'),
        ),
    ]
