# Generated by Django 3.1.1 on 2020-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0008_auto_20200929_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(default='Deactive', max_length=30),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='status',
            field=models.CharField(default='Deactive', max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(default='Deactive', max_length=30),
        ),
    ]
