# Generated by Django 3.1.1 on 2020-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0009_auto_20200930_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='unit',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='animalshippingfee',
            name='unit',
            field=models.CharField(default='kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='materialshippingfee',
            name='unit',
            field=models.CharField(default='kg', max_length=5),
        ),
    ]
