# Generated by Django 3.1.1 on 2020-10-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0010_auto_20201004_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
    ]
