# Generated by Django 3.1.1 on 2020-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0012_animal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age_range',
        ),
    ]
