# Generated by Django 3.1.1 on 2020-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0013_remove_animal_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/animals'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/chemicals'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/coffee'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/materials'),
        ),
    ]
