# Generated by Django 3.1.1 on 2020-10-14 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0015_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('billing_address_no', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('street_name_house_number', models.CharField(max_length=60)),
                ('apartment_name', models.CharField(blank=True, max_length=60, null=True)),
                ('city_town', models.CharField(max_length=60)),
                ('state_country', models.CharField(max_length=50)),
                ('zip_post_code', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='products_ordered')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('classification', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('product_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profiles'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_address_no', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('street_name_house_number', models.CharField(max_length=60)),
                ('apartment_name', models.CharField(blank=True, max_length=60, null=True)),
                ('city_town', models.CharField(max_length=60)),
                ('state_country', models.CharField(max_length=50)),
                ('zip_post_code', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='kwetuTrade.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('amount_ordered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordered_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('out_of_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(default='pending', max_length=50)),
                ('newness_order_status', models.CharField(default='new', max_length=50)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='kwetuTrade.billingaddress')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='kwetuTrade.customer')),
                ('ordered_products', models.ManyToManyField(related_name='order_items', to='kwetuTrade.OrderItem')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='kwetuTrade.shippingaddress')),
            ],
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='kwetuTrade.customer'),
        ),
    ]
