# Generated by Django 3.1.1 on 2020-10-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0016_auto_20201014_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
