# Generated by Django 3.1.1 on 2020-10-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0018_auto_20201027_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='kwetuTrade.customer'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='kwetuTrade.customer'),
        ),
    ]
