# Generated by Django 3.1.1 on 2020-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0019_auto_20201027_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
