# Generated by Django 3.1.1 on 2020-11-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0021_auto_20201106_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotonsite',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordernotonsite',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordernotonsite',
            name='email_address',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ordernotonsite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
