# Generated by Django 3.1.1 on 2020-11-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0023_auto_20201107_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotonsiteitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/special_order'),
        ),
    ]
