# Generated by Django 3.1.1 on 2020-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0024_auto_20201107_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_ordered/images'),
        ),
        migrations.AlterField(
            model_name='ordernotonsiteitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_order/images'),
        ),
    ]
