# Generated by Django 3.1.1 on 2020-11-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0025_auto_20201107_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='advert_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='advert',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
