# Generated by Django 3.1.1 on 2020-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0026_auto_20201108_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adverts/images'),
        ),
    ]
