# Generated by Django 3.1.1 on 2020-11-14 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0029_auto_20201109_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderInvoice',
            fields=[
                ('invoice_id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_file', models.FileField(upload_to='customers/orders/invoices')),
            ],
        ),
    ]
