# Generated by Django 3.1.1 on 2020-11-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0030_customerorderinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderinvoice',
            old_name='invoice_id',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='customerorderinvoice',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='customerorderinvoice',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='kwetuTrade.order'),
        ),
    ]
