# Generated by Django 3.1.1 on 2020-11-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuTrade', '0031_auto_20201114_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderinvoice',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='kwetuTrade.order'),
        ),
    ]
